cluster:
    enabled: true

service:
    type: LoadBalancer

minio:
    enabled: false

externalS3:
    enabled: true
    host: storage.googleapis.com
    port: 443
    rootPath: milvus/my-release
    bucketName: fenui-411701
    cloudProvider: gcp
    useSSL: true
    accessKey: "GOOGIQ4N4JXFLRYHU2ENRZMP"
    secretKey: "V+X4FnMvH3rhl8GgoiFLXiFb//utmHl6mjjQTIrm"
